[providers]
node = { version = "18" }

[phases.setup]
nixPkgs = ["nodejs_18", "npm", "cargo", "rustc"]

[phases.install]
cmds = ["npm install --omit=optional --omit=dev"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "node simple-api.js"
