nodeLinker: node-modules
npmAuditRegistry: "https://registry.npmjs.org"
yarnPath: .yarn/releases/yarn-4.3.1.cjs
supportedArchitectures:
  cpu:
    - ia32
    - x64
    - arm
    - arm64
    - freebsd
    - macos
    - windows
    - linux
    - gnu
    - musl