nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
yarnPath: .yarn/releases/yarn-4.3.1.cjs
supportedArchitectures:
  cpu:
    - ia32
    - x64
    - arm
    - arm64
  os:
    - freebsd
    - macos
    - windows
    - linux
  libc:
    - gnu
    - musl