[package]
edition = "2021"
name = "spider-rs_spider-rs"
version = "0.0.0"
description = "The fastest web crawler written in Rust ported to nodejs."
repository = "https://github.com/spider-rs/spider-nodejs"
authors = ["j-mendez <jeff@a11ywatch.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
compact_str = "0.7.1"
indexmap = "2.1.0"
napi = { version = "2.16.1", default-features = false, features = ["napi4", "async", "tokio_rt", "serde-json"] }
napi-derive = "2.16.1"
num_cpus = "1.16.0"
serde = "1"
serde_json = "1"
spider = { version = "1.95.22", features = ["napi", "budget", "cron", "regex", "cookies", "socks", "chrome", "control", "chrome_intercept", "cache", "openai", "serde", "real_browser" ] }

[target.x86_64-unknown-linux-gnu.dependencies]
openssl-sys = { version = "0.9.96", features = ["vendored"] }
openssl = { version = "0.10.60", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = { version = "0.9.96", features = ["vendored"] }
openssl = { version = "0.10.60", features = ["vendored"] }

[build-dependencies]
napi-build = "2.1.2"

[profile.release]
lto = true
